#!/usr/bin/env python3
"""
Real-kernel replication of the targeted-collision attack (paper 4.1.1).

Phase 1 showed, in Python, that an adversary who knows the sketch's hash
seeds can construct identities that collide with a victim's cell in every
row and inflate the victim's estimated wakeup count by ~440%. That was a
white-box result in a simulation. This asks whether it reproduces against
a sketch living in a real kernel, and -- the part that actually decides
something -- whether it reproduces for every identity-key candidate.

WHAT THIS MEASURES

  The victim's exact count is truth. The victim's sketch estimate is what
  the scheduler would act on. The attack succeeds to the extent it drives
  those apart while the victim's own behaviour is unchanged.

  Both numbers come from the kernel's own query via the cms_probe map,
  not from a reimplementation here, so a bug in this script cannot
  manufacture a result. Phase 1 was bitten by exactly that failure: a
  collision search that hardcoded the wrong hash produced a convincing
  "this hash is immune" finding that was entirely an artifact.

THREAT MODEL, STATED HONESTLY

  The seeds are generated by bpf_get_prandom_u32() inside the kernel and
  live in a BPF map. Reading them requires privilege. An ordinary
  unprivileged attacker therefore CANNOT run the white-box attack, which
  is a meaningful difference from the Python model where seed knowledge
  was simply assumed.

  So two attacks are run:

    white-box   attacker knows the seeds. Models an insider, a leak, or
                a system where seeds are predictable. Tests whether the
                mechanism transfers to a real kernel at all.

    blind       attacker knows only the hash function, which is public
                in the source. No seed knowledge. This is what an
                unprivileged co-located process can actually do.

  Reporting only the white-box number would overstate the risk; reporting
  only the blind one would understate what an insider can do.
"""

import argparse
import ctypes
import json
import os
import subprocess
import sys
import time

FNV32_BASIS = 0x811C9DC5
FNV32_PRIME = 0x01000193
FNV64_BASIS = 0xCBF29CE484222325
FNV64_PRIME = 0x100000001B3
COMM_LEN = 16


def fnv1a_comm(name: bytes) -> int:
    """Identity for --identity-key comm. Mirrors identity.bpf.c.

    The kernel hashes the full 16-byte comm buffer including the NUL
    padding, so a short name must be padded here or the identities will
    not match and every collision search will silently fail.
    """
    buf = name[:COMM_LEN].ljust(COMM_LEN, b"\0")
    h = FNV64_BASIS
    for byte in buf:
        h = ((h ^ byte) * FNV64_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def sketch_col(identity: int, seed: int, width: int) -> int:
    """Column an identity lands in for one row. Mirrors sketch.bpf.c."""
    h = (FNV32_BASIS ^ seed) & 0xFFFFFFFF
    for i in range(8):
        h = ((h ^ ((identity >> (i * 8)) & 0xFF)) * FNV32_PRIME) & 0xFFFFFFFF
    return h % width


def bpftool(*args) -> str:
    return subprocess.run(
        ["sudo", "bpftool", *args], capture_output=True, text=True, check=True
    ).stdout


def map_id(name: str) -> int:
    """Find a map by name AND owning process.

    Selecting by name alone is not safe: several loaded programs have a
    map called bpf_bpf.bss, and bpftool silently returns whichever comes
    first. A leftover scxtop was enough to make the seed lookup read an
    unrelated program's memory and find nothing.
    """
    for m in json.loads(bpftool("map", "show", "-j")):
        if m.get("name") != name:
            continue
        if any(p.get("comm") == "scx_cms" for p in m.get("pids", [])):
            return m["id"]
    raise RuntimeError(f"no map {name!r} owned by scx_cms; is the scheduler running?")


def read_probe() -> dict:
    out = json.loads(bpftool("map", "dump", "id", str(map_id("cms_probe")), "-j"))
    entry = out[0]
    return entry.get("formatted", entry)["value"]


def set_probe_pid(pid: int) -> None:
    """Point the probe at a pid, zeroing the accumulated counts.

    Value size is read from the map itself rather than hardcoded: a
    previous version hardcoded 40 bytes, and it silently went stale the
    moment probe.bpf.c's struct grew (diagnostic fields added while
    chasing the never-undercount bug) -- the exact class of drift this
    project keeps getting bitten by.
    """
    mid = map_id("cms_probe")
    info = json.loads(bpftool("map", "show", "id", str(mid), "-j"))
    value_size = info["bytes_value"]
    value = list(pid.to_bytes(4, "little")) + [0] * (value_size - 4)
    bpftool(
        "map", "update", "id", str(mid),
        "key", "0", "0", "0", "0",
        "value", *[f"0x{b:02x}" for b in value],
    )


def read_bss() -> dict:
    """Flatten the scheduler's .bss into a plain name -> value dict."""
    out = json.loads(bpftool("map", "dump", "id", str(map_id("bpf_bpf.bss")), "-j"))
    entry = out[0]
    value = entry.get("formatted", entry)["value"]
    entries = value[".bss"] if isinstance(value, dict) and ".bss" in value else value
    flat = {}
    for item in entries:
        flat.update(item)
    return flat


IDENTITY_NAMES = {0: "pid", 1: "tgid", 2: "comm"}


def read_identity_key() -> str:
    """Which identity the running scheduler is actually keyed on.

    Read from the kernel rather than taken from this script's arguments,
    because those can disagree. An earlier run of this harness reported a
    convincing result for `pid` that was really the previous `comm`
    scheduler still attached: the new one had failed to start, and nothing
    in the output said which one was being measured. The tell was an
    identity of 0x978e38b91e4927fd where a pid should have been.
    """
    out = json.loads(bpftool("map", "dump", "id", str(map_id("bpf_bpf.rodata")), "-j"))
    entry = out[0]
    value = entry.get("formatted", entry)["value"]
    entries = value[".rodata"] if isinstance(value, dict) and ".rodata" in value else value
    flat = {}
    for item in entries:
        flat.update(item)
    key = flat.get("cms_identity_key")
    return IDENTITY_NAMES.get(int(key), f"unknown({key})") if key is not None else "unknown"


def read_seeds() -> list:
    """Per-buffer, per-row seeds from the scheduler's .bss.

    This read requires privilege, which is exactly the distinction between
    the white-box and blind attacks: an unprivileged process cannot do it.
    """
    seeds = read_bss().get("cms_sketch_seeds")
    if seeds is None:
        raise RuntimeError("cms_sketch_seeds not present; run with --tracker sketch")
    return seeds


def find_colliding_comms(victim_id: int, seeds: list, width: int, depth: int,
                         wanted: int, budget: int = 500000) -> list:
    """Search for comm strings colliding with the victim in ANY row.

    Colliding in all rows at once is ~1-in-width^depth and infeasible by
    design -- that is precisely what depth is for. The attack instead
    finds keys that collide in one row each and fires enough of them that
    every row is poisoned, which is what makes the minimum-across-rows
    rise.
    """
    targets = [sketch_col(victim_id, seeds[0][row], width) for row in range(depth)]
    found = []
    per_row = {row: 0 for row in range(depth)}
    quota = max(1, wanted // depth)

    for n in range(budget):
        name = b"atk%d" % n
        ident = fnv1a_comm(name)
        for row in range(depth):
            if per_row[row] >= quota:
                continue
            if sketch_col(ident, seeds[0][row], width) == targets[row]:
                found.append((name.decode(), row))
                per_row[row] += 1
                break
        if len(found) >= wanted:
            break

    # A silently short search would weaken the attack while still
    # reporting success -- Phase 1 added a check for this after finding
    # the same hazard (paper Section 4.1.5).
    short = [r for r, c in per_row.items() if c < quota]
    if short:
        print(f"  WARNING: collision search under-delivered for rows {short} "
              f"(budget {budget} exhausted). Attack is weaker than requested.",
              file=sys.stderr)

    return found


def set_comm(name: str) -> None:
    libc = ctypes.CDLL("libc.so.6", use_errno=True)
    buf = ctypes.create_string_buffer(name.encode()[:COMM_LEN - 1])
    libc.prctl(15, ctypes.byref(buf), 0, 0, 0)  # PR_SET_NAME


def waker(name: str | None, wakes_per_sec: float, duration: float) -> None:
    """A process that does nothing but wake up at a fixed rate."""
    if name:
        set_comm(name)
    interval = 1.0 / wakes_per_sec
    end = time.time() + duration
    while time.time() < end:
        time.sleep(interval)


def spawn(name: str | None, rate: float, duration: float) -> int:
    pid = os.fork()
    if pid == 0:
        try:
            waker(name, rate, duration)
        finally:
            os._exit(0)
    return pid


def sample(seconds: float) -> tuple:
    """Let the probe accumulate, then read the victim's two counts."""
    time.sleep(seconds)
    p = read_probe()
    return int(p["exact"]), int(p["sketch"])


def report(label: str, exact: int, sketch: int) -> float:
    over = (sketch - exact) / exact * 100.0 if exact else 0.0
    print(f"  {label:<12} exact={exact:<6} sketch={sketch:<6} "
          f"overestimate={over:+.1f}%")
    return over


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--width", type=int, default=256)
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--attackers", type=int, default=64,
                    help="colliding processes to spawn")
    ap.add_argument("--attacker-rate", type=float, default=200.0,
                    help="wakeups per second per attacker")
    ap.add_argument("--victim-rate", type=float, default=20.0)
    ap.add_argument("--settle", type=float, default=3.0,
                    help="seconds to sample each phase")
    ap.add_argument("--mode", choices=["white-box", "blind"], default="white-box")
    args = ap.parse_args()

    if os.geteuid() != 0:
        print("needs root: reads BPF maps", file=sys.stderr)
        return 1

    print(f"Targeted-collision attack, mode={args.mode}, "
          f"sketch {args.width}x{args.depth}\n")

    identity_key = read_identity_key()
    print(f"  scheduler is keyed on: {identity_key}")

    victim = spawn("victim", args.victim_rate, 120)
    time.sleep(0.5)
    set_probe_pid(victim)
    print(f"  victim pid {victim}, probe attached")

    base_exact, base_sketch = sample(args.settle)
    baseline = report("baseline", base_exact, base_sketch)

    if args.mode == "white-box":
        if identity_key != "comm":
            # The targeted attack needs the attacker to CHOOSE its identity.
            # Only comm is self-settable; a pid or tgid is assigned by the
            # kernel, so there is no way to steer yourself into a victim's
            # cell. This is not a limitation of the harness -- it is the
            # asymmetry the identity-key decision turns on, so it is
            # reported as a result rather than worked around.
            print(f"\n  targeted attack is not available against "
                  f"identity-key={identity_key}:")
            print( "  an attacker cannot choose its own pid/tgid, so it cannot")
            print( "  construct an identity that collides with the victim's cells.")
            print( "  Falling back to blind volume for comparison.\n")
            names = [f"blind{i}" for i in range(args.attackers)]
        else:
            seeds = read_seeds()
            probe = read_probe()
            victim_id = int(probe["identity"])
            print(f"  victim identity 0x{victim_id:x}, seeds read from kernel")
            colliding = find_colliding_comms(victim_id, seeds, args.width,
                                             args.depth, args.attackers)
            print(f"  found {len(colliding)} colliding comms")
            names = [name for name, _ in colliding]
    else:
        # No seed knowledge: the attacker can only generate volume and
        # hope. This is what an unprivileged process can actually do.
        names = [f"blind{i}" for i in range(args.attackers)]
        print(f"  no seed knowledge; spraying {len(names)} identities")

    attackers = [spawn(n, args.attacker_rate, args.settle + 5) for n in names]
    print(f"  spawned {len(attackers)} attackers")

    atk_exact, atk_sketch = sample(args.settle)
    attacked = report("under attack", atk_exact, atk_sketch)

    for pid in attackers:
        try:
            os.kill(pid, 9)
            os.waitpid(pid, 0)
        except (ProcessLookupError, ChildProcessError):
            pass
    try:
        os.kill(victim, 9)
        os.waitpid(victim, 0)
    except (ProcessLookupError, ChildProcessError):
        pass

    print(f"\n  inflation from attack: {attacked - baseline:+.1f} "
          f"percentage points")
    return 0


if __name__ == "__main__":
    sys.exit(main())
